server:
  port: 7000
  
spring:
  application:
    name: aconsumer
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://nsxym.top:7200/eureka
      
logging:
  level:
    root: info
    com.t: debug