server:
  port: 7000
  
spring:
  application:
    name: aconsumer
eureka:
  instance:
    ip-address: true
  client:
    service-url:
      defaultZone: http://nsxym.top:7200/eureka
      
logging:
  level:
    root: info
    com.t: debug