server:
  port: 7001
  
spring:
  application:
    name: provider1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nsxym.top:3306/zhrun?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
       # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,log4j
  #rabbitmq配置
  rabbitmq:
    host: nsxym.top
    port: 7202
  #redis配置
  redis:
    host: nsxym.top
    port: 7201

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://nsxym.top:7200/eureka
      
logging:
  level:
    root: info
    com.t: debug