server:
  port: 7001
  
spring:
  application:
    name: provider1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nsxym.top:3306/zhrun?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456

  #rabbitmq配置
  rabbitmq:
    host: nsxym.top
    port: 7202
  #redis配置
  redis:
    host: nsxym.top
    port: 7201
  zipkin:
    base-url: http://nsxym.top:7203
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1


feign:
  hystrix:
    enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://nsxym.top:7200/eureka
      
logging:
  level:
    root: info
    com.t: debug